{{-  $t2vMistral := and (index .Values "modules" "text2vec-mistral" "enabled") (index .Values "modules" "text2vec-mistral" "apiKey") -}}
{{-  $generativeMistral := and (index .Values "modules" "generative-mistral" "enabled") (index .Values "modules" "generative-mistral" "apiKey") }}
{{-  $mistral := or ($t2vMistral) ($generativeMistral) }}
{{- if $mistral }}

{{- $apiKeys := list }}
{{- if $t2vMistral }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "text2vec-mistral" "apiKey") -}}
{{- end }}
{{- if $generativeMistral }}
  {{- $apiKeys = append $apiKeys (index .Values "modules" "generative-mistral" "apiKey") -}}
{{- end }}

{{- if gt (len ($apiKeys | uniq)) 1 -}}
  {{- fail "Mistral modules activated, but their keys differ. Use the same key on all activated Mistral modules." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: weaviate-mistral
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  apiKey: {{ index $apiKeys 0 | b64enc }}
{{ end }}
