{{-  $t2vDatabricks := and (index .Values "modules" "text2vec-databricks" "enabled") (index .Values "modules" "text2vec-databricks" "token") -}}
{{-  $generativeDatabricks := and (index .Values "modules" "generative-databricks" "enabled") (index .Values "modules" "generative-databricks" "token") }}
{{-  $databricks := or ($t2vDatabricks) ($generativeDatabricks) }}
{{- if $databricks }}

{{- $tokens := list }}
{{- if $t2vDatabricks }}
  {{- $tokens = append $tokens (index .Values "modules" "text2vec-databricks" "token") -}}
{{- end }}
{{- if $generativeDatabricks }}
  {{- $tokens = append $tokens (index .Values "modules" "generative-databricks" "token") -}}
{{- end }}

{{- if gt (len ($tokens | uniq)) 1 -}}
  {{- fail "Databricks modules activated, but their tokens differ. Use the same token on all activated Databricks modules." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: weaviate-databricks
  labels:
    app.kubernetes.io/name: weaviate
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  token: {{ index $tokens 0 | b64enc }}
{{ end }}
